 --Q1. TOTAL REVENUE GENERATED BY Male vs Female customers?
 select gender, SUM(purchase_amount) as revenue from mytable group by gender;

 --Q2. WHICH CUSTOMERS USED A DISCOUNT BUT STILL SPENT MORE THAN AVERAGE PURCHASE AMOUNT?
select customer_id, purchase_amount from mytable where discount_applied='Yes' and purchase_amount >= (select AVG(purchase_amount) from mytable);


 --Q3. TOP 5 PRODUCTS WITH HIGHEST AVERAGE REVIEW RATING?
select item_purchased, AVG(review_rating) as "Average Product Rating" from mytable group by item_purchased order by avg(review_rating) desc limit 5;


 --Q4. COMPARING AVG PURCHASE AMOUNT b/w STANDARD AND EXPRESS SHIPPING
 select shipping_type, ROUND(AVG(purchase_amount),2) from mytable where shipping_type in ('Standard','Express') group by shipping_type;


 --Q5. DO SUBSCRIBED CUSTOMERS SPEND MORE?
 select subscription_status, COUNT(customer_id) as total_customers,ROUND(AVG(purchase_amount),2) as avg_spend,ROUND(SUM(purchase_amount),2) as total_revenue from mytable group by subscription_status order by total_revenue, avg_spend desc;


 --Q6. WHICH 5 PRODUCTS HAVE HIGHEST % OF PURCHASES WITH DISCOUNTS APPLIED
 select item_purchased,ROUND(SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100,2) as discount_rate from mytable group by item_purchased order by discount_rate desc limit 5;


 --Q7. DIVIDING CUSTOMERS INTO NEW,RETURNING,LOYAL BASED ON THEIR TOTAL NO OF PREVIOUS PURCHASES
 with customer_type as (select customer_id, previous_purchases,case when previous_purchases=1 then 'NEW' when previous_purchases between 2 and 10 then 'RETURNING' else 'LOYAL' end as customer_segment from mytable) select customer_segment, count(*) as "no of customers" from customer_type group by customer_segment;


 --Q8. ARE REPEAT BUYER CUSTOMERS(MORE THAN 5 PREVIOUS PURCHASES) ALSO LIKELY TO SUBSCRIBE?
 select subscription_status, count(customer_id) as repeat_buyers from mytable where previous_purchases > 5 group by subscription_status;


 --Q9. REVENUE CONTRIBUTION OF EACH AGE GROUP?
 select age_group, SUM(purchase_amount) as total_revenue from mytable group by age_group order by total_revenue desc;
